### ISSUE TITLE
Evocrash demo does not complete Gradle execution after reporting it has finished

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/EvoCrash#15]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: Evocrash latest version
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Evocrash execution using Gradlew (Demo example) does not finished (ends execution) after reporting completion, when Evocrash is not able to generate crash replicating tests. It finishes correctly when it succeeds in generating the tests.
In both cases, Evocrash should ends normally, reporting the results.

#### Steps to reproduce
See #13 for an example of Evocrash execution that does not succeed and does not ends normally.
In this case, last Evocrash output is:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>GGA was done in 1001!<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

! Budget exceeded
! Unable to cover goal 0 org.crash.client.crashcoverage.CrashCoverageTestFitness@1fc4ecc8
* Search finished after 1001s, 1001 statements, best individual has fitness 0.0
* Covered 0/1 goals
* Target exception was set to: Exception in thread "main" java.lang.ClassCastException
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> callBadIdea
[MASTER] 10:05:48.804 [logback-1] WARN  TimeController - Phase INITIALIZATION lasted too long, 883 seconds more than allowed.
* Target exception was set to: Exception in thread "main" java.lang.ClassCastException
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> callBadIdea
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion CRASH
* Target exception was set to: Exception in thread "main" java.lang.ClassCastException
* EvoCrash: The target call is either public or protected!
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> The retrived call(s) to inject in the tests are:
>>>>>> callBadIdea
* Coverage of criterion CRASH: 0%
* Total number of goals: 1
* Number of covered goals: 0
* Generated 0 tests with total length 0
* Resulting test suite's coverage: 0%
* Generating assertions
* Resulting test suite's mutation score: 0%
* Compiling and checking tests
* Permissions denied during test execution: 
  - java.lang.RuntimePermission: 
         writeFileDescriptor: 1
* Writing JUnit test case 'MyObject_ESTest' to src/GGA-tests/java
* Done!

* Computation finished
Exception in thread "main" java.lang.AssertionError: expected:<0.0> but was:<3.0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at org.junit.Assert.assertEquals(Assert.java:683)
        at eu.stamp_project.evocrash.demo.TestCreation.create(TestCreation.java:97)
        at eu.stamp_project.evocrash.demo.Application.main(Application.java:6)
> Building 75% > :run
```
As you can see, Evocrash execution is blocked on Gradle (75% execution) and it does not finish.

#### Relationships
#13 

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by xdevroey** [comment]
Requires update of Gradle demo with botsing
